apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chartproxy
spec:
  interval: 5m
  chart:
    spec:
      chart: helm-charts-oci-proxy
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: chartproxy
  # https://github.com/container-registry/helm-charts-oci-proxy/blob/main/chart/values.yaml
  values: {}
