apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plantuml
  namespace: flux-system
  labels:
    app.kubernetes.io/sops: enabled
    app.kubernetes.io/post-build-variables: enabled
spec:
  interval: 1m
  targetNamespace: plantuml
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: plantuml
  prune: true
  wait: true
