apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: traefik
spec:
  forwardAuth:
    address: ${traefik_forward_auth_address}
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
    tls:
      insecureSkipVerify: ${traefik_forward_auth_tls_insecure_skip_verify:=false}
      certSecret: cluster-issuer-certificate-tls
