apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gha-runner-scale-set-controller
  namespace: flux-system
  labels:
    app.kubernetes.io/sops: enabled
    app.kubernetes.io/post-build-variables: enabled
spec:
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: gha-runner-scale-set-controller
  prune: true
  wait: true
