apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: redis
      version: 18.18.0
      sourceRef:
        kind: HelmRepository
        name: redis
  # https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
  values:
    auth:
      password: ${redis_password}
    master:
      persistence:
        enabled: ${redis_master_persistence_enabled:=false}
    replica:
      persistence:
        enabled: ${redis_replica_persistence_enabled:=false}
