apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - releases.yaml
  - variables.yaml

patches:
  - target:
      kind: Kustomization
      labelSelector: app.kubernetes.io/sops=enabled
    patch: |
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: all
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-age
  - target:
      kind: Kustomization
      labelSelector: app.kubernetes.io/post-build-variables=enabled
    patch: |
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: all
      spec:
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: variables
            - kind: Secret
              name: variables-sensitive
