apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: variables
  namespace: flux-system
  labels:
    app.kubernetes.io/sops: enabled
spec:
  interval: 30s
  dependsOn: []
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: clusters/oci-artifacts/variables
  prune: true
  wait: true
