# You need to encrypt this file with SOPS manually.
# ksail sops --encrypt variables-sensitive.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: variables-sensitive
stringData:
    cloudflared_tunnel_token: ENC[AES256_GCM,data:aYQKb+/f3CBJvxtJyB8v9zx5ag5t5ZG0xnPHeiIiyJLYXIL7mvhPj007LJXX/kQvUd02GGns/uJ/TL3fgpY1VGlE7HemtW1oHKDQ56Sq1dl6m/TFfKywXP8MHArMV3tDVY3YOGIZOoP9SKNJ4NwaqJBzPRAwzTUTFaDnCxYsIVsjyc0qJYXrvVl5Rgs+vbk+BdfsrcK5G46vaklQ3lO4qfYAmnUM9iV2r3mpToCiBEZH/Xw9MfYhCw==,iv:57YOLhbotfovrF4WuwMyQ4wgTnqAflMO2mJkMQiOxXE=,tag:kOYxjsECgHKbcajBHoPBMw==,type:str]
    github_token: ENC[AES256_GCM,data:ootGaenaFMjy2M7GybLWJenf1q9BU/89JAna02OIgtTQeFfzm69Ozw==,iv:ytcrfJZ1Ksrrd6IMWb4r9vWeloRoMnpW3cS3xaLK9UQ=,tag:TzM6fgRyiQrFO94x5bgQAg==,type:str]
    oauth2_proxy_client_secret: ENC[AES256_GCM,data:+FLKaG6z4zyPnaLM6ZBlIEHquT9T35RL1iE19RWoGuGokNTudgpGgg==,iv:EX3RpokaCqJFZuf7Ub25ZatI/p2d52e/bXxlfukK+Mo=,tag:dBZl9Eq6wOpzJu04i+NRdQ==,type:str]
    oauth2_proxy_cookie_secret: ENC[AES256_GCM,data:UIFuEL7UUgfpAZMoMWyIcpFilC98Vg7iwZjH0yHYrKDIi9oiQKMNEZSZTw4=,iv:eaQbFJGdmfuqlkHIomchP0PjE0Kds9a4nYThInK/YmE=,tag:uaG37DekxG7YAPsA8G7OFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age120p4hfdjg4x84rcl50vaus77l6rvpqyfjw23lszcpa089asr4s4qrtytwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOGd4Y2tCWjRsajlkcEkw
            enBpTUlkZjJPMGJZVmF5SDZERGlGTUFuRGhrCmEyV3dha0UwMlkyYitLUCtrUTZ1
            bzE3dWQwNERLeWFHWEhwNElsZWRpaGcKLS0tIGhvYmpKVFlEaVQxUTlxUnZMRUtm
            MWFkY0htcnhsWVJhcURkak5ka05YaVEKH3pe5xJJfVvuNcCcu4H5ZYnVEER2bKlk
            DRUxf8dSznjBBr5D5oeQ/n40yTAuu6XAtj8sQIi0kE6vyFOS6AewYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-10T01:18:36Z"
    mac: ENC[AES256_GCM,data:EN09g4i03XLXxH/ZjFzRn1suQ9ZF1LO9feUWtGXG0c5GkK2gzPmLOdpfCDSfsz/2myEO1rca29f6AnvJWxXvoEiPNLlw2+dCbZ435EOR8F48YjGx4Ewzs14vo29jPdU3JhWZj2l/ZipnsJrhIstsnIlQ/uGHg9oaDWhiqJ1J9ZY=,iv:rU96vGqpfHwA2fFmgV8Fn3BhTEofFwatBEEOoDm9GRU=,tag:XF9PlwQg1tKY18BQ2ffBqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
