kind: Secret
apiVersion: v1
metadata:
  name: mysql
  namespace: fleetdm
stringData:
  mysql-root-password: ${fleetdm_mysql_password:=fleetdm}
  mysql-replication-password: ${fleetdm_mysql_password:=fleetdm}
  mysql-password: ${fleetdm_mysql_password:=fleetdm}
