apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fleetdm
  namespace: fleetdm
spec:
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: fleet
      version: v6.2.0
      sourceRef:
        kind: HelmRepository
        name: fleetdm
  # https://github.com/fleetdm/fleet/blob/main/charts/fleet/values.yaml
  values:
    resources: {}
    hostName: fleetdm.${cluster_domain}
    ingress:
      enabled: true
      hosts:
        - host: fleetdm.${cluster_domain}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: {}
    fleet:
      tls:
        enabled: false
    database:
      address: fleetdm-mysql.fleetdm:3306
    cache:
      address: fleetdm-redis-master.fleetdm:6379
      usePassword: true
    mysql:
      enabled: true
      auth:
        createDatabase: true
        database: fleet
        username: fleet
        existingSecret: mysql
    redis:
      enabled: true
      auth:
        existingSecret: redis
        existingSecretPasswordKey: redis-password
