apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fleetdm
  namespace: fleetdm
spec:
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: fleetdm
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: fleetdm
  # https://github.com/fleetdm/fleet/blob/main/charts/fleet/values.yaml
  values:
    resources: {}
    hostName: fleetdm.${cluster_domain}
    ingress:
      enabled: true
      hosts:
        - host: fleetdm.${cluster_domain}
          paths:
            - path: /
              pathType: ImplementationSpecific
