apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth-headers
  namespace: traefik
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: ${cluster_domain}
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
