apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: operator
      version: 5.0.10
      sourceRef:
        kind: HelmRepository
        name: minio
  # https://github.com/minio/operator/blob/master/helm/operator/values.yaml
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: minio-operator
  chart:
    spec:
      chart: tenant
      version: 5.0.10
      sourceRef:
        kind: HelmRepository
        name: minio
  # https://github.com/minio/operator/blob/master/helm/tenant/values.yaml
  values: {}
