apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llama-gpt
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml

configMapGenerator:
  - name: llama-gpt
    literals:
      - DEFAULT_MODEL="/models/llama-2-7b-chat.bin"
      - OPENAI_API_HOST="http://llama-gpt-api.llama-gpt:8000"
      - OPENAI_API_KEY="sk-XXXXXXXXXXXXXXXXXXXX"
      - WAIT_HOSTS="llama-gpt-api.llama-gpt:8000"
      - WAIT_TIMEOUT="600"
