apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: cilium
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: cilium
  # https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
  values:
    kubeProxyReplacement: true
