apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webhook-receiver
  namespace: flux-system
spec:
  routes:
    - kind: Rule
      match: Host(`flux-webhook.${cluster_domain}`)
      services:
        - kind: Service
          name: webhook-receiver
          port: 80
  tls: {}
