apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: selfsigned-cluster-issuer
  namespace: flux-system
  labels:
    app.kubernetes.io/sops: enabled
    app.kubernetes.io/post-build-variables: enabled
spec:
  interval: 1m
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: cert-manager/cluster-issuers/selfsigned
  prune: true
  wait: true
