apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-services
  namespace: flux-system
spec:
  interval: 1m
  dependsOn: 
    - name: variables
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: infrastructure/services
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom: 
      - kind: ConfigMap
        name: variables
      - kind: Secret
        name: variables-sensitive
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-configs
  namespace: flux-system
spec:
  interval: 1m
  dependsOn: 
    - name: infrastructure-services
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: infrastructure/configs
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom: 
      - kind: ConfigMap
        name: variables
      - kind: Secret
        name: variables-sensitive
