apiVersion: v1
kind: Namespace
metadata:
  name: reloader
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    goldilocks.fairwinds.com/vpa-update-mode: "auto"
    goldilocks.fairwinds.com/vpa-min-replicas: "1"
