apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: dex
  # https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
  values:
    ingress:
      enabled: true
      hosts:
        - host: dex.${cluster_domain}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: dex-cert
          hosts:
            - dex.${cluster_domain}

    config:
      issuer: https://dex.${cluster_domain}
      storage:
        type: memory
      enablePasswordDB: true
