apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ksail-pipeline
  namespace: tekton
spec:
  description: |
    This pipeline clones a git repo containing a KSail project, and then provisions and tests that the KSail cluster can reconcile.
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
    - name: ksail-project
      type: string
      description: The name of the KSail project to reconcile.
  workspaces:
    - name: shared-data
      description: |
        This workspace contains the cloned repo files, so they can be read by the
        next task.
    - name: git-credentials
      description: Your SSH credentials
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
        - name: ssh-directory
          workspace: git-credentials
      params:
        - name: url
          value: $(params.repo-url)
    - name: ksail-up
      runAfter:
        - checkout
      taskRef:
        name: ksail
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: args
          value: up $(params.ksail-project)
    - name: ksail-down
      runAfter:
        - ksail-up
      taskRef:
        name: ksail
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: args
          value: down $(params.ksail-project)
