apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ksail
  namespace: tekton
spec:
  params:
    - name: args
      type: string
      description: The arguments to pass to the ksail command.
  steps:
    - name: ksail
      image: ghcr.io/devantler/ksail
      args:
        - $(params.args)
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: docker
      name: docker
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: { }
    - name: dind-socket
      emptyDir: { }
