apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudflared
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: cloudflared
  # https://github.com/cloudflare/helm-charts/blob/main/charts/cloudflare-tunnel-remote/values.yaml
  values:
    cloudflare:
      tunnel_token: ${cloudflared_tunnel_token}
