apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-letsencrypt-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    server: ${letsencrypt_server}
    email: ${letsencrypt_email}
    privateKeySecretRef:
      name: cloudflare-letsencrypt-cluster-issuer-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-dns-api-key
              key: api-token
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-api-key
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ${cloudflare_dns_api_key}
