apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: traefik
      version: 28.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  values:
    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        asDefault: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: cluster-issuer-certificate-tls
    service:
      type: ${traefik_service_type:=ClusterIP}
      spec:
        loadBalancerIP: ${traefik_ingress_load_balancer_ip}
    ingressRoute:
      dashboard:
        matchRule: Host(`traefik.${cluster_domain}`)
        entryPoints:
          - websecure
