apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gha-runner-scale-set-controller
  namespace: gha-runner-scale-set-controller
spec:
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
