apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gha-runner-scale-set-controller
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/actions/actions-runner-controller-charts
