apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeshark
spec:
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: kubeshark
      version: 52.3.69
      sourceRef:
        kind: HelmRepository
        name: kubeshark
  # https://github.com/kubeshark/kubeshark/blob/master/helm-chart/values.yaml
  values:
    tap:
      ingress:
        enabled: true
        host: kubeshark.${cluster_domain}
