apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: flux-system
  labels:
    app.kubernetes.io/sops: enabled
    app.kubernetes.io/post-build-variables: enabled
spec:
  interval: 1m
  targetNamespace: oauth2-proxy
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: oauth2-proxy
  prune: true
  wait: true
  patches:
    - target:
        kind: HelmRelease
        name: oauth2-proxy
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: oauth2-proxy
        spec:
          values:
            config:
              configFile: |-
                provider="github"
                email_domains=["*"]
                github_users=["devantler"]
                reverse_proxy=true
                upstreams=["static://202"]
                skip_provider_button=true
                cookie_domains=[".${cluster_domain}"]
