apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: variables
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: ./.test/services
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: variables
