apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: variables
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: ./.test/variables
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
