apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: oauth2-proxy
      version: 7.7.9
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  # https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml
  values:
    deploymentAnnotations:
      configmap.reloader.stakater.com/reload: oauth2-proxy
    ingress:
      enabled: ${oauth2_proxy_ingress_enabled:=true}
      hosts:
        - oauth2-proxy.${cluster_domain}
    config:
      clientID: ${oauth2_proxy_client_id}
      clientSecret: ${oauth2_proxy_client_secret}
      cookieSecret: ${oauth2_proxy_cookie_secret}
      cookieName: ${oauth2_proxy_cookie_name:=}
