apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-pipeline
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: tekton-pipeline
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: tekton-pipeline
  # https://github.com/cdfoundation/tekton-pipeline-helm-chart/blob/main/charts/tekton-pipeline-pipeline/values.yaml
  values: {}
