apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  interval: 1m
  chart:
    spec:
      chart: trivy-operator
      version: 0.24.1
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
  # https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml
  values: {}
