apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeshark
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: kubeshark
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: kubeshark
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: variables
      - kind: Secret
        name: variables-sensitive
