apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8sgpt-operator
spec:
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: k8sgpt-operator
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: k8sgpt-operator
  # https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/chart/operator/values.yaml
  values: {}
