name: Test

on:
  pull_request:
    branches: [main]
    # Added 'edited' temporarily, as there currently is no trigger for when the base branch is updated.
    # https://github.com/orgs/community/discussions/64119
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - closed
      - edited
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  KSAIL_CLUSTER_NAME: oci-artifacts-ksail

jobs:
  test:
    runs-on: oci-artifacts
    if: github.event.pull_request.draft == false
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@v4
      - name: ⚙️ Install wget
        run: sudo apt-get install -y wget
      - name: ⚙️ Install KSail
        run: |
          sudo wget -qO /usr/local/bin/ksail "https://getbin.io/devantler/ksail?os=linux&arch=arm64"
          sudo chmod +x /usr/local/bin/ksail
      - name: ⛴️ Provision cluster
        run: |
          ksail sops ${{ env.KSAIL_CLUSTER_NAME }} --import "${{ secrets.KSAIL_SOPS_KEY }}"
          ksail up ${{ env.KSAIL_CLUSTER_NAME }}
      - name: 🔥 Teardown cluster
        if: always()
        run: ksail down ${{ env.KSAIL_CLUSTER_NAME }}
